version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/:/iwatchseries-api/src/
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodbdata:/data/db
      - ./docker-scripts/:/docker-entrypoint-initdb.d
volumes:
  mongodbdata:
